import Head from "next/head";
import Header from "../components/Header";

import { getSession, signIn } from "next-auth/react";
import Sidebar from "../components/Sidebar";

import Feed from "../components/Feed";
import Widgets from "../components/Widgets";

export default function Home({ session }) {
  if (!session) {
    signIn();
  } else {
    return (
      <div>
        <Head>
          <title>Facebook Clone</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className="flex bg-gray-100">
          {/* Sidebar */}
          <Sidebar />
          {/* Feed */}
          <Feed />
          {/* Widgets */}
          <Widgets />
        </main>
      </div>
    );
  }
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
};
